workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic CI
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Disable Swift Package Manager
        script: flutter config --no-enable-swift-package-manager
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Build iOS
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Internal Testers"

  android-release:
    name: Android Release Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Generate key.properties
        script: |
          echo "storePassword=$CM_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android/key.properties
          echo "storeFile=whosbehind_keystore.jks" >> android/key.properties
      - name: Decode Keystore
        script: |
          if [ -n "$CM_KEYSTORE" ]; then
            echo "$CM_KEYSTORE" | base64 --decode > android/whosbehind_keystore.jks
          fi
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build Android App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
