workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic CI
    environment:
      flutter: stable
      xcode: latest
      groups:
        - REVENUECAT_KEYS
      ios_signing:
        provisioning_profiles:
          - whos_behind_appstore_v3
        certificates:
          - legacyflow_dist
    scripts:
      - name: Disable Swift Package Manager
        script: flutter config --no-enable-swift-package-manager
      - name: Generate .env file
        script: |
          echo "REVENUECAT_API_KEY=$REVENUECAT_API_KEY" > .env
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Set up export options plist
        script: |
          plutil -replace MinimumOSVersion -string "13.0" ios/Flutter/AppFrameworkInfo.plist
          cat > export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>V573KVW28N</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.sampeng.whosbehind</key>
                  <string>whos behind ios_app_store 1780014496</string>
              </dict>
          </dict>
          </plist>
          EOF
      - name: Build iOS
        script: flutter build ipa --release --export-options-plist=export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Internal Testers"

  android-release:
    name: Android Release Workflow
    instance_type: mac_mini_m2
    environment:
      groups:
        - android_signing
      flutter: stable
    scripts:
      - name: Generate key.properties
        script: |
          echo "storePassword=$CM_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android/key.properties
          echo "storeFile=whosbehind_keystore.jks" >> android/key.properties
      - name: Generate .env file
        script: |
          echo "REVENUECAT_API_KEY=$REVENUECAT_API_KEY" > .env
          echo "REVENUECAT_API_KEY_ANDROID=$REVENUECAT_API_KEY_ANDROID" >> .env
      - name: Decode Keystore
        script: |
          if [ -n "$CM_KEYSTORE" ]; then
            echo "$CM_KEYSTORE" | base64 --decode > android/whosbehind_keystore.jks
          fi
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build Android App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
