name: whos_behind
description: A new Flutter project for anti-fraud evidence collection.
publish_to: 'none'

version: 1.0.6+17

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  image: ^4.1.3
  provider: ^6.0.5
  shared_preferences: ^2.3.0
  sqflite_common_ffi: ^2.4.0+3
  http: ^1.6.0
  permission_handler: ^12.0.1
  firebase_core: ^4.8.0
  firebase_storage: ^13.4.0
  geolocator: ^14.0.2
  pdf: ^3.12.0
  printing: ^5.14.3
  purchases_flutter: ^10.7.0
  firebase_remote_config: ^6.5.0
  flutter_dotenv: ^5.1.0
  webview_flutter: ^4.4.4
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#8B0000"
  adaptive_icon_foreground: "app_icon.png"
