import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:geolocator/geolocator.dart';

class PdfGeneratorService {
  static Future<void> generateEvidenceReport({
    required BuildContext context,
    XFile? selectedImage,
    required String evidenceTimestamp,
    String? uploadedImageUrl,
    String? selectedObservation,
    String? otherObservation,
    String? searchedPhone,
    Map<String, bool?>? phoneSearchStatus,
    String? anchorUrl,
  }) async {
    try {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Generating PDF, please wait...')),
        );
      }

      Position? pos;
      try {
        LocationPermission permission = await Geolocator.checkPermission();
        if (permission == LocationPermission.denied) {
          permission = await Geolocator.requestPermission();
        }
        if (permission == LocationPermission.whileInUse ||
            permission == LocationPermission.always) {
          pos = await Geolocator.getCurrentPosition(
              locationSettings: const LocationSettings(accuracy: LocationAccuracy.high));
        }
      } catch (e) {
        debugPrint("Location access failed or was skipped: $e");
      }

      pw.MemoryImage? pdfImage;
      if (selectedImage != null) {
        final bytes = await selectedImage.readAsBytes();
        pdfImage = pw.MemoryImage(bytes);
      }
      final font = await PdfGoogleFonts.notoSansRegular();
      final fontBold = await PdfGoogleFonts.notoSansBold();
      
      final titleStyle = pw.TextStyle(font: fontBold, fontSize: 16, color: PdfColors.red900);
      final subtitleStyle = pw.TextStyle(font: fontBold, fontSize: 13, color: PdfColors.black);
      final labelStyle = pw.TextStyle(font: fontBold, fontSize: 10, color: PdfColors.grey900);
      final contentStyle = pw.TextStyle(font: font, fontSize: 10, color: PdfColors.black);
      
      final pdf = pw.Document();
      final reportId = DateTime.now().millisecondsSinceEpoch.toString();

      // GPS Strings
      String gpsZh = "用戶未提供";
      String gpsEn = "Not provided";
      if (pos != null) {
        gpsZh = "經度: ${pos.longitude}\n緯度: ${pos.latitude}\n精準度: ${pos.accuracy.toStringAsFixed(1)}公尺";
        gpsEn = "Longitude: ${pos.longitude}\nLatitude: ${pos.latitude}\nAccuracy: ${pos.accuracy.toStringAsFixed(1)}m";
      }

      // Incident Type
      String incidentTypeZh = searchedPhone != null ? "可疑電話號碼散布 / 詐騙防範" : "肖像權侵害 / 圖片遭盜用鑑定";
      String incidentTypeEn = searchedPhone != null ? "Suspicious Phone Number Distribution / Anti-Scam Lookup" : "Right of Portrait Infringement / Image Misuse Verification";

      // Platforms
      String platformZh = searchedPhone != null 
          ? "公開網路搜尋（Google, Facebook, Dcard, PTT, Threads）"
          : "公開網路以圖搜圖（Google Lens, TinEye, Bing Visual Search, Google Images）";
      String platformEn = searchedPhone != null
          ? "Public Web Search (Google, Facebook, Dcard, PTT, Threads)"
          : "Public Web Image Search (Google Lens, TinEye, Bing Visual Search, Google Images)";

      // Image Search Result
      String imageSearchZh = "無（本案為電話號碼查詢）";
      String imageSearchEn = "N/A (This report is for Phone Number Lookup)";
      if (selectedImage != null) {
        final observation = selectedObservation == '其他 / Other' ? (otherObservation ?? '') : (selectedObservation ?? '');
        imageSearchZh = "查核結果: $observation\n雲端存證連結: ${uploadedImageUrl ?? '無雲端連結'}";
        imageSearchEn = "Observation: $observation\nSecure Image URL: ${uploadedImageUrl ?? 'N/A'}";
      }

      // Phone Lookup Result
      String phoneLookupZh = "無（本案為圖片盜用查詢）";
      String phoneLookupEn = "N/A (This report is for Image Misuse Verification)";
      if (searchedPhone != null) {
        final yesCount = phoneSearchStatus?.values.where((v) => v == true).length ?? 0;
        final noCount = phoneSearchStatus?.values.where((v) => v == false).length ?? 0;
        phoneLookupZh = "查詢號碼: $searchedPhone\n有紀錄平台數: $yesCount\n無紀錄平台數: $noCount";
        phoneLookupEn = "Searched Number: $searchedPhone\nFound on: $yesCount platforms\nNo record on: $noCount platforms";
      }

      // 165 Report Status
      String scamReportZh = searchedPhone != null
          ? "已提供官方 165 檢舉入口指引；若比對有紀錄，建議儘速舉報。"
          : "已提供官方 165 檢舉及社群平台（FB/IG/Threads）申訴指引。";
      String scamReportEn = searchedPhone != null
          ? "Official 165 Anti-Scam report guide provided; immediate reporting recommended if records found."
          : "Official 165 Anti-Scam and social media (FB/IG/Threads) take-down guides provided.";

      // Legal Notice
      String legalNoticeZh = "本文件由「誰在亂搞？」App 自動產出。時間與定位資訊為技術性存證，供司法機關參考。本工具之查詢範圍僅限於公開網頁，不包括私密通訊或非公開社群數據。";
      String legalNoticeEn = "This report is generated by Who's Behind? App. The timestamp and GPS coordinates are technical evidence for legal reference. The search scope is limited to publicly indexed web pages and does not cover private communications or closed social networks.";

      // Helper for clean rendering of fields
      pw.Widget buildField(String label, String content) {
        return pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 8),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(label, style: labelStyle),
              pw.SizedBox(height: 1),
              pw.Text(content, style: contentStyle),
            ],
          ),
        );
      }

      pw.Widget buildUrlLink(String prefix, String url, {double fontSize = 9}) {
        String safeUrl = url.replaceAll('？', '?').replaceAll('，', ',');
        String displayUrl = safeUrl
            .replaceAll('/', '/ ')
            .replaceAll('=', '= ')
            .replaceAll('?', '? ')
            .replaceAll('&', '& ')
            .replaceAll(',', ', ');

        return pw.Wrap(
          children: [
            if (prefix.isNotEmpty)
              pw.Text(prefix, style: pw.TextStyle(font: font, fontSize: fontSize, color: PdfColors.black)),
            pw.UrlLink(
              destination: safeUrl,
              child: pw.Text(displayUrl, style: pw.TextStyle(font: font, fontSize: fontSize, color: PdfColors.blue)),
            ),
          ],
        );
      }

      // Reusable Bilingual Footer
      pw.Widget buildBilingualFooter() {
        return pw.Container(
          alignment: pw.Alignment.center,
          margin: const pw.EdgeInsets.only(top: 15),
          padding: const pw.EdgeInsets.only(top: 8),
          decoration: const pw.BoxDecoration(
            border: pw.Border(
              top: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
            ),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                '本文件由「誰在亂搞？」App 自動產出，具法律參考效力\nGenerated by Who\'s Behind? App for legal reference',
                style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey700),
              ),
              pw.Text(
                'Report ID: $reportId',
                style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey700),
              ),
            ],
          ),
        );
      }

      // Reusable Core Message Banner
      pw.Widget buildCoreMessageBanner() {
        return pw.Container(
          padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 12),
          decoration: pw.BoxDecoration(
            color: PdfColors.red50,
            border: pw.Border.all(color: PdfColors.red200, width: 0.5),
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.center,
            children: [
              pw.Text(
                '你有證據，才有正義   |   Evidence is the foundation of justice',
                style: pw.TextStyle(font: fontBold, fontSize: 10, color: PdfColors.red900),
              ),
            ],
          ),
        );
      }

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          footer: (pw.Context context) => buildBilingualFooter(),
          build: (pw.Context context) {
            return [
              // Header banner
              buildCoreMessageBanner(),
              pw.SizedBox(height: 16),
              
              // Side-by-side Columns
              pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  // Left Column: zh-TW
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('技術存證報告 (Technical Evidence)', style: titleStyle),
                        pw.SizedBox(height: 10),
                        buildField('報告編號', reportId),
                        buildField('產出時間', evidenceTimestamp),
                        buildField('GPS 位置（選填）', gpsZh),
                        buildField('事件類型', incidentTypeZh),
                        buildField('涉及平台', platformZh),
                        buildField('反向搜圖結果', imageSearchZh),
                        buildField('電話查詢結果', phoneLookupZh),
                        buildField('165 通報狀態', scamReportZh),
                        buildField('法律聲明', legalNoticeZh),
                      ],
                    ),
                  ),
                  pw.SizedBox(width: 24),
                  // Right Column: en-US
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('Forensic Evidence Report', style: titleStyle),
                        pw.SizedBox(height: 10),
                        buildField('Report ID', reportId),
                        buildField('Date Generated', evidenceTimestamp),
                        buildField('GPS Location (Optional)', gpsEn),
                        buildField('Incident Type', incidentTypeEn),
                        buildField('Platform Involved', platformEn),
                        buildField('Reverse Image Search Result', imageSearchEn),
                        buildField('Phone Number Lookup Result', phoneLookupEn),
                        buildField('165 Anti-Scam Report Status', scamReportEn),
                        buildField('Legal Notice', legalNoticeEn),
                      ],
                    ),
                  ),
                ],
              ),
              
              if (pos != null) ...[
                pw.SizedBox(height: 12),
                pw.Text('定位地圖連結 / Google Maps Link:', style: labelStyle),
                pw.SizedBox(height: 2),
                buildUrlLink('', 'https://maps.google.com/?q=${pos.latitude},${pos.longitude}', fontSize: 10),
              ],
              
              if (pdfImage != null) ...[
                pw.SizedBox(height: 16),
                pw.Text('存證圖片證據 / Image Evidence:', style: labelStyle),
                pw.SizedBox(height: 8),
                pw.Container(
                  height: 160,
                  alignment: pw.Alignment.centerLeft,
                  child: pw.Image(pdfImage, fit: pw.BoxFit.contain),
                ),
              ],
            ];
          },
        ),
      );

      // Page 2: Legal Assessment & Action Guide
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          footer: (pw.Context context) => buildBilingualFooter(),
          build: (pw.Context context) {
            return [
              buildCoreMessageBanner(),
              pw.SizedBox(height: 16),
              
              pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  // Left Column: zh-TW
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('法律救濟評估與行動指南', style: titleStyle),
                        pw.SizedBox(height: 12),
                        
                        pw.Text('法律依據 / Legal Basis:', style: subtitleStyle),
                        pw.SizedBox(height: 6),
                        buildField('• 肖像權侵害 (民法第18、195條)', '未經授權公開散布或使用他人照片即構成肖像權侵害，被害人得請求移除內容並請求精神慰撫金之損害賠償。'),
                        buildField('• 隱私權與個資保護 (個資法違反)', '惡意於公開網路平台散布私人聯絡方式（如電話號碼）屬違反個人資料保護法，應負擔民刑事賠償責任。'),
                        buildField('• 2年請求權時效 (民法第197條)', '自主張權利人知悉損害及賠償義務人起，二年間不行使而消滅。'),
                        
                        pw.SizedBox(height: 10),
                        pw.Text('緊急行動清單 / Action Checklist:', style: subtitleStyle),
                        pw.SizedBox(height: 6),
                        buildField('1. 平台檢舉要求下架', '立即前往 Facebook, Instagram, Threads 等官方侵權投訴頁面，要求移除被盜用照片。'),
                        buildField('2. 寄送存證信函', '利用本報告檢附之警告信草稿（第三頁）填寫資訊寄送，表明您的法律立場。'),
                        buildField('3. 保存技術證據', '妥善保管本報告，其隨附之 Report ID、GPS 定位與時間戳記均可作為司法機關偵辦參考。'),
                        buildField('4. 警政單位舉報', '若懷疑遭遇網絡詐騙、貼圖威脅，應撥打 165 反詐騙專線，或攜帶本報告至派出所報案。'),
                      ],
                    ),
                  ),
                  pw.SizedBox(width: 24),
                  // Right Column: en-US
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('Legal Assessment & Action Guide', style: titleStyle),
                        pw.SizedBox(height: 12),
                        
                        pw.Text('Legal Basis:', style: subtitleStyle),
                        pw.SizedBox(height: 6),
                        buildField('• Right of Portrait (Civil Code §18, 195)', 'Unauthorized distribution or usage of personal photos constitutes a civil infringement. Victims may demand content removal and claim mental agony damages.'),
                        buildField('• Privacy & Personal Data (PDPA Violation)', 'Maliciously distributing private contact details (e.g. mobile numbers) on public websites violates the Personal Data Protection Act, carrying civil and criminal liabilities.'),
                        buildField('• 2-Year Statute of Limitations (Civil Code §197)', 'Claims for civil damages must be initiated within two years from discovery of the infringement.'),
                        
                        pw.SizedBox(height: 10),
                        pw.Text('Action Checklist:', style: subtitleStyle),
                        pw.SizedBox(height: 6),
                        buildField('1. Platform Takedown Requests', 'Immediately submit take-down complaints to Facebook, Instagram, or Threads to remove unauthorized contents.'),
                        buildField('2. Send Legal Notice', 'Draft and send the Cease and Desist warning notice (on Page 3) to formalize your legal rights.'),
                        buildField('3. Preserve Technical Evidence', 'Retain this PDF report. The included Report ID, timestamp, and GPS logs serve as authentic evidence for law enforcement.'),
                        buildField('4. Report to Law Enforcement', 'Contact the official 165 Anti-Scam Hotline or visit local police station with this report to initiate official investigation.'),
                      ],
                    ),
                  ),
                ],
              ),
            ];
          },
        ),
      );

      // Page 3: Cease and Desist Draft (English warning letter)
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          footer: (pw.Context context) => buildBilingualFooter(),
          build: (pw.Context context) {
            return [
              pw.Header(
                level: 0,
                child: pw.Text('Legal Notice / Cease and Desist Draft', style: titleStyle),
              ),
              pw.SizedBox(height: 16),
              pw.Text('Evidence ID / Report ID: $reportId', style: pw.TextStyle(font: fontBold, fontSize: 12)),
              pw.Text('Evidence Timestamp: $evidenceTimestamp', style: pw.TextStyle(font: font, fontSize: 11)),
              pw.Text('GPS Coordinates: ${pos != null ? "${pos.latitude}, ${pos.longitude}" : "Not provided by user"}', style: pw.TextStyle(font: font, fontSize: 11)),
              pw.SizedBox(height: 20),
              
              pw.Text('To the Infringer / Target Entity:', style: pw.TextStyle(font: fontBold, fontSize: 12)),
              pw.SizedBox(height: 10),
              pw.Text(
                'It has been officially documented and authenticated on the above date that you have, without prior authorization or consent, publicly distributed and/or misused personal portrait photos and/or private contact information on public online platforms (including but not limited to Facebook, Instagram, Threads, PTT, or other websites).',
                style: pw.TextStyle(font: font, fontSize: 10.5, color: PdfColors.black),
              ),
              pw.SizedBox(height: 10),
              pw.Text(
                'This unauthorized action violates civil rights regarding portrait rights under Civil Code Articles 18, 184, 195, and personal data protections under the Personal Data Protection Act (PDPA) of Taiwan (R.O.C.).',
                style: pw.TextStyle(font: font, fontSize: 10.5, color: PdfColors.black),
              ),
              pw.SizedBox(height: 10),
              pw.Text(
                'YOU ARE HEREBY NOTIFIED to complete the following demands within seven (7) days of this notice:',
                style: pw.TextStyle(font: fontBold, fontSize: 11, color: PdfColors.red900),
              ),
              pw.SizedBox(height: 8),
              pw.Bullet(text: 'Immediately REMOVE all unauthorized profile photos, text posts, contact numbers, and other associated content from all platforms.', style: pw.TextStyle(font: font, fontSize: 10.5)),
              pw.Bullet(text: 'Provide a formal written confirmation to cease all ongoing and future infringements.', style: pw.TextStyle(font: font, fontSize: 10.5)),
              pw.Bullet(text: 'Propose a reasonable settlement compensation for the mental agony and privacy violations incurred.', style: pw.TextStyle(font: font, fontSize: 10.5)),
              pw.SizedBox(height: 12),
              pw.Text(
                'Failure to comply with these demands within the specified timeline will result in immediate civil actions and criminal reporting to local law enforcement. All legal expenses, including attorney fees and forensic costs, will be sought at your expense.',
                style: pw.TextStyle(font: font, fontSize: 10.5),
              ),
              pw.SizedBox(height: 30),
              
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: const pw.BoxDecoration(
                  color: PdfColors.grey100,
                  borderRadius: pw.BorderRadius.all(pw.Radius.circular(6)),
                ),
                child: pw.Text(
                  'Important Notice: This legal draft is auto-generated by Who\'s Behind? App based on technical logs. For formal court proceedings or legal mailing, it is highly recommended to consult a licensed attorney.',
                  style: pw.TextStyle(font: font, fontSize: 8.5, color: PdfColors.grey700, fontStyle: pw.FontStyle.italic),
                ),
              ),
            ];
          },
        ),
      );

      final pdfBytes = await pdf.save();
      await Printing.sharePdf(
          bytes: pdfBytes, filename: 'evidence_report_$reportId.pdf');
    } catch (e) {
      debugPrint("PDF Generation Failed: $e");
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to generate PDF: $e')),
        );
      }
    }
  }
}
